# Generated by Django 5.0.1 on 2024-03-24 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.product')),
            ],
        ),
    ]
